//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityPropeller
{
    [Serializable]
    public class BackStatusMsg : Message
    {
        public const string k_RosMessageName = "unity_propeller_msgs/BackStatus";
        public override string RosMessageName => k_RosMessageName;

        public float realpose_dm3410;
        public float realpose_dm3910_1;
        public float realpose_dm3910_2;
        public float realpose_dm3910_3;

        public BackStatusMsg()
        {
            this.realpose_dm3410 = 0.0f;
            this.realpose_dm3910_1 = 0.0f;
            this.realpose_dm3910_2 = 0.0f;
            this.realpose_dm3910_3 = 0.0f;
        }

        public BackStatusMsg(float realpose_dm3410, float realpose_dm3910_1, float realpose_dm3910_2, float realpose_dm3910_3)
        {
            this.realpose_dm3410 = realpose_dm3410;
            this.realpose_dm3910_1 = realpose_dm3910_1;
            this.realpose_dm3910_2 = realpose_dm3910_2;
            this.realpose_dm3910_3 = realpose_dm3910_3;
        }

        public static BackStatusMsg Deserialize(MessageDeserializer deserializer) => new BackStatusMsg(deserializer);

        private BackStatusMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.realpose_dm3410);
            deserializer.Read(out this.realpose_dm3910_1);
            deserializer.Read(out this.realpose_dm3910_2);
            deserializer.Read(out this.realpose_dm3910_3);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.realpose_dm3410);
            serializer.Write(this.realpose_dm3910_1);
            serializer.Write(this.realpose_dm3910_2);
            serializer.Write(this.realpose_dm3910_3);
        }

        public override string ToString()
        {
            return "BackStatusMsg: " +
            "\nrealpose_dm3410: " + realpose_dm3410.ToString() +
            "\nrealpose_dm3910_1: " + realpose_dm3910_1.ToString() +
            "\nrealpose_dm3910_2: " + realpose_dm3910_2.ToString() +
            "\nrealpose_dm3910_3: " + realpose_dm3910_3.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
