//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityPropeller
{
    [Serializable]
    public class TargetPoseMsg : Message
    {
        public const string k_RosMessageName = "unity_propeller_msgs/TargetPose";
        public override string RosMessageName => k_RosMessageName;

        public float targetpose_dm3410;
        public float targetpose_dm3910_1;
        public float targetpose_dm3910_2;
        public float targetpose_dm3910_3;
        public int rov_pwm;

        public TargetPoseMsg()
        {
            this.targetpose_dm3410 = 0.0f;
            this.targetpose_dm3910_1 = 0.0f;
            this.targetpose_dm3910_2 = 0.0f;
            this.targetpose_dm3910_3 = 0.0f;
            this.rov_pwm = 0;
        }

        public TargetPoseMsg(float targetpose_dm3410, float targetpose_dm3910_1, float targetpose_dm3910_2, float targetpose_dm3910_3, int rov_pwm)
        {
            this.targetpose_dm3410 = targetpose_dm3410;
            this.targetpose_dm3910_1 = targetpose_dm3910_1;
            this.targetpose_dm3910_2 = targetpose_dm3910_2;
            this.targetpose_dm3910_3 = targetpose_dm3910_3;
            this.rov_pwm = rov_pwm;
        }

        public static TargetPoseMsg Deserialize(MessageDeserializer deserializer) => new TargetPoseMsg(deserializer);

        private TargetPoseMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.targetpose_dm3410);
            deserializer.Read(out this.targetpose_dm3910_1);
            deserializer.Read(out this.targetpose_dm3910_2);
            deserializer.Read(out this.targetpose_dm3910_3);
            deserializer.Read(out this.rov_pwm);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.targetpose_dm3410);
            serializer.Write(this.targetpose_dm3910_1);
            serializer.Write(this.targetpose_dm3910_2);
            serializer.Write(this.targetpose_dm3910_3);
            serializer.Write(this.rov_pwm);
        }

        public override string ToString()
        {
            return "TargetPoseMsg: " +
            "\ntargetpose_dm3410: " + targetpose_dm3410.ToString() +
            "\ntargetpose_dm3910_1: " + targetpose_dm3910_1.ToString() +
            "\ntargetpose_dm3910_2: " + targetpose_dm3910_2.ToString() +
            "\ntargetpose_dm3910_3: " + targetpose_dm3910_3.ToString() +
            "\nrov_pwm: " + rov_pwm.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
