
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2080006
     no. of nonzeroes in the factor l        =        12471025
     ratio of nonzeroes in factor (min/max)  =          0.7775
     number of super nodes                   =            1976
     maximum order of a front matrix         =             879
     maximum size of a front matrix          =          386760
     maximum size of a front trapezoid       =          344274
     no. of floating point ops for factor    =      3.5602D+09
     no. of floating point ops for solve     =      4.6462D+07
     ratio of flops for factor (min/max)     =          0.5990
     ratio of allocated memory (max/min)     =          1.1678
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.005940
     time (cpu & wall) for ordering          =        0.125000        0.124891
     time (cpu & wall) for other matrix prep =        0.031250        0.034287
     time (cpu & wall) for value input       =        0.031250        0.025522
     time (cpu & wall) for matrix distrib.   =        0.078125        0.073401
     time (cpu & wall) for numeric factor    =        0.140625        0.138038
     computational rate (gflops) for factor  =       25.316895       25.791364
     time (cpu & wall) for numeric solve     =        0.015625        0.011042
     computational rate (gflops) for solve   =        2.973549        4.207726
     effective I/O rate (GB/sec) for solve   =       11.078214       15.676244

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        294912.        2. MB        264601.        2. MB
                95-   1        262144.        2. MB        229626.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        557056.        4. MB        494227.        4. MB


  Solver Memory allocated on core    0       =      140.304 MB
  Solver Memory allocated on core    1       =      120.146 MB
  Total Solver Memory allocated by all cores =      260.450 MB





  Performance statistics for DSP solver: icalls =      2

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2080330
     no. of nonzeroes in the factor l        =        12427069
     ratio of nonzeroes in factor (min/max)  =          0.7608
     number of super nodes                   =            1967
     maximum order of a front matrix         =             861
     maximum size of a front matrix          =          371091
     maximum size of a front trapezoid       =          325941
     no. of floating point ops for factor    =      3.5522D+09
     no. of floating point ops for solve     =      9.2771D+07
     ratio of flops for factor (min/max)     =          0.5663
     ratio of allocated memory (max/min)     =          1.1766
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.015625        0.011116
     time (cpu & wall) for ordering          =        0.093750        0.100619
     time (cpu & wall) for other matrix prep =        0.015625        0.011557
     time (cpu & wall) for value input       =        0.046875        0.043306
     time (cpu & wall) for matrix distrib.   =        0.140625        0.150361
     time (cpu & wall) for numeric factor    =        0.156250        0.149204
     computational rate (gflops) for factor  =       22.734084       23.807661
     time (cpu & wall) for numeric solve     =        0.015625        0.011565
     computational rate (gflops) for solve   =        5.937355        8.021996
     effective I/O rate (GB/sec) for solve   =       22.120127       29.886635

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        294912.        2. MB        262798.        2. MB
                95-   1        262144.        2. MB        229835.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        557056.        4. MB        492633.        4. MB


  Solver Memory allocated on core    0       =      140.647 MB
  Solver Memory allocated on core    1       =      119.537 MB
  Total Solver Memory allocated by all cores =      260.183 MB





  Performance statistics for DSP solver: icalls =      3

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2080330
     no. of nonzeroes in the factor l        =        12427069
     ratio of nonzeroes in factor (min/max)  =          0.7608
     number of super nodes                   =            1967
     maximum order of a front matrix         =             861
     maximum size of a front matrix          =          371091
     maximum size of a front trapezoid       =          325941
     no. of floating point ops for factor    =      3.5522D+09
     no. of floating point ops for solve     =      9.2771D+07
     ratio of flops for factor (min/max)     =          0.5663
     ratio of allocated memory (max/min)     =          1.1766
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.019497
     time (cpu & wall) for matrix distrib.   =        0.062500        0.063898
     time (cpu & wall) for numeric factor    =        0.140625        0.131675
     computational rate (gflops) for factor  =       25.260094       26.977053
     time (cpu & wall) for numeric solve     =        0.015625        0.010896
     computational rate (gflops) for solve   =        5.937355        8.514241
     effective I/O rate (GB/sec) for solve   =       22.120127       31.720538

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        294912.        2. MB        262798.        2. MB
                95-   1        262144.        2. MB        229835.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        557056.        4. MB        492633.        4. MB


  Solver Memory allocated on core    0       =      140.647 MB
  Solver Memory allocated on core    1       =      119.537 MB
  Total Solver Memory allocated by all cores =      260.183 MB





  Performance statistics for DSP solver: icalls =      4

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2080735
     no. of nonzeroes in the factor l        =        12559676
     ratio of nonzeroes in factor (min/max)  =          0.7667
     number of super nodes                   =            1975
     maximum order of a front matrix         =             882
     maximum size of a front matrix          =          389403
     maximum size of a front trapezoid       =          346917
     no. of floating point ops for factor    =      3.6815D+09
     no. of floating point ops for solve     =      1.3956D+08
     ratio of flops for factor (min/max)     =          0.5749
     ratio of allocated memory (max/min)     =          1.2042
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.015625        0.011016
     time (cpu & wall) for ordering          =        0.093750        0.092253
     time (cpu & wall) for other matrix prep =        0.015625        0.012086
     time (cpu & wall) for value input       =        0.031250        0.039671
     time (cpu & wall) for matrix distrib.   =        0.109375        0.129358
     time (cpu & wall) for numeric factor    =        0.125000        0.126723
     computational rate (gflops) for factor  =       29.451697       29.051185

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        294912.        2. MB        264577.        2. MB
                95-   1        262144.        2. MB        230138.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        557056.        4. MB        494715.        4. MB


  Solver Memory allocated on core    0       =      144.720 MB
  Solver Memory allocated on core    1       =      120.181 MB
  Total Solver Memory allocated by all cores =      264.901 MB





  Performance statistics for DSP solver: icalls =      5

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2080735
     no. of nonzeroes in the factor l        =        12559676
     ratio of nonzeroes in factor (min/max)  =          0.7667
     number of super nodes                   =            1975
     maximum order of a front matrix         =             882
     maximum size of a front matrix          =          389403
     maximum size of a front trapezoid       =          346917
     no. of floating point ops for factor    =      3.6815D+09
     no. of floating point ops for solve     =      1.3956D+08
     ratio of flops for factor (min/max)     =          0.5749
     ratio of allocated memory (max/min)     =          1.2042
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.018914
     time (cpu & wall) for matrix distrib.   =        0.062500        0.061487
     time (cpu & wall) for numeric factor    =        0.125000        0.128797
     computational rate (gflops) for factor  =       29.451697       28.583424
     time (cpu & wall) for numeric solve     =        0.015625        0.009717
     computational rate (gflops) for solve   =        8.932145       14.362357
     effective I/O rate (GB/sec) for solve   =       33.277474       53.508195

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        294912.        2. MB        264577.        2. MB
                95-   1        262144.        2. MB        230138.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        557056.        4. MB        494715.        4. MB


  Solver Memory allocated on core    0       =      144.720 MB
  Solver Memory allocated on core    1       =      120.181 MB
  Total Solver Memory allocated by all cores =      264.901 MB





  Performance statistics for DSP solver: icalls =      6

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2080735
     no. of nonzeroes in the factor l        =        12559676
     ratio of nonzeroes in factor (min/max)  =          0.7667
     number of super nodes                   =            1975
     maximum order of a front matrix         =             882
     maximum size of a front matrix          =          389403
     maximum size of a front trapezoid       =          346917
     no. of floating point ops for factor    =      3.6815D+09
     no. of floating point ops for solve     =      1.3956D+08
     ratio of flops for factor (min/max)     =          0.5749
     ratio of allocated memory (max/min)     =          1.2042
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.019426
     time (cpu & wall) for matrix distrib.   =        0.062500        0.063486
     time (cpu & wall) for numeric factor    =        0.140625        0.140855
     computational rate (gflops) for factor  =       26.179286       26.136483
     time (cpu & wall) for numeric solve     =        0.015625        0.009917
     computational rate (gflops) for solve   =        8.932145       14.073710
     effective I/O rate (GB/sec) for solve   =       33.277474       52.432818

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        294912.        2. MB        264577.        2. MB
                95-   1        262144.        2. MB        230138.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        557056.        4. MB        494715.        4. MB


  Solver Memory allocated on core    0       =      144.720 MB
  Solver Memory allocated on core    1       =      120.181 MB
  Total Solver Memory allocated by all cores =      264.901 MB





  Performance statistics for DSP solver: icalls =      7

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2080735
     no. of nonzeroes in the factor l        =        12559676
     ratio of nonzeroes in factor (min/max)  =          0.7667
     number of super nodes                   =            1975
     maximum order of a front matrix         =             882
     maximum size of a front matrix          =          389403
     maximum size of a front trapezoid       =          346917
     no. of floating point ops for factor    =      3.6815D+09
     no. of floating point ops for solve     =      1.3956D+08
     ratio of flops for factor (min/max)     =          0.5749
     ratio of allocated memory (max/min)     =          1.2042
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.019354
     time (cpu & wall) for matrix distrib.   =        0.078125        0.075799
     time (cpu & wall) for numeric factor    =        0.218750        0.218501
     computational rate (gflops) for factor  =       16.829541       16.848696
     time (cpu & wall) for numeric solve     =        0.015625        0.013163
     computational rate (gflops) for solve   =        8.932145       10.602567
     effective I/O rate (GB/sec) for solve   =       33.277474       39.500773

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        294912.        2. MB        264577.        2. MB
                95-   1        262144.        2. MB        230138.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        557056.        4. MB        494715.        4. MB


  Solver Memory allocated on core    0       =      144.720 MB
  Solver Memory allocated on core    1       =      120.181 MB
  Total Solver Memory allocated by all cores =      264.901 MB





  Performance statistics for DSP solver: icalls =      8

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2080735
     no. of nonzeroes in the factor l        =        12559676
     ratio of nonzeroes in factor (min/max)  =          0.7667
     number of super nodes                   =            1975
     maximum order of a front matrix         =             882
     maximum size of a front matrix          =          389403
     maximum size of a front trapezoid       =          346917
     no. of floating point ops for factor    =      3.6815D+09
     no. of floating point ops for solve     =      1.3956D+08
     ratio of flops for factor (min/max)     =          0.5749
     ratio of allocated memory (max/min)     =          1.2042
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.031250        0.035540
     time (cpu & wall) for matrix distrib.   =        0.062500        0.070913
     time (cpu & wall) for numeric factor    =        0.171875        0.171252
     computational rate (gflops) for factor  =       21.419416       21.497325
     time (cpu & wall) for numeric solve     =        0.015625        0.012499
     computational rate (gflops) for solve   =        8.932145       11.166074
     effective I/O rate (GB/sec) for solve   =       33.277474       41.600170

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        294912.        2. MB        264577.        2. MB
                95-   1        262144.        2. MB        230138.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        557056.        4. MB        494715.        4. MB


  Solver Memory allocated on core    0       =      144.720 MB
  Solver Memory allocated on core    1       =      120.181 MB
  Total Solver Memory allocated by all cores =      264.901 MB





  Performance statistics for DSP solver: icalls =      9

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2080735
     no. of nonzeroes in the factor l        =        12559676
     ratio of nonzeroes in factor (min/max)  =          0.7667
     number of super nodes                   =            1975
     maximum order of a front matrix         =             882
     maximum size of a front matrix          =          389403
     maximum size of a front trapezoid       =          346917
     no. of floating point ops for factor    =      3.6815D+09
     no. of floating point ops for solve     =      1.3956D+08
     ratio of flops for factor (min/max)     =          0.5749
     ratio of allocated memory (max/min)     =          1.2042
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.008120
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.020641
     time (cpu & wall) for matrix distrib.   =        0.046875        0.069929
     time (cpu & wall) for numeric factor    =        0.218750        0.268347
     computational rate (gflops) for factor  =       16.829541       13.719026
     time (cpu & wall) for numeric solve     =        0.015625        0.033016
     computational rate (gflops) for solve   =        8.932145        4.227147
     effective I/O rate (GB/sec) for solve   =       33.277474       15.748601

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        294912.        2. MB        264577.        2. MB
                95-   1        262144.        2. MB        230138.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        557056.        4. MB        494715.        4. MB


  Solver Memory allocated on core    0       =      144.721 MB
  Solver Memory allocated on core    1       =      120.181 MB
  Total Solver Memory allocated by all cores =      264.902 MB





  Performance statistics for DSP solver: icalls =     10

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2081032
     no. of nonzeroes in the factor l        =        12577181
     ratio of nonzeroes in factor (min/max)  =          0.7530
     number of super nodes                   =            1966
     maximum order of a front matrix         =             849
     maximum size of a front matrix          =          360825
     maximum size of a front trapezoid       =          282975
     no. of floating point ops for factor    =      3.6957D+09
     no. of floating point ops for solve     =      1.8645D+08
     ratio of flops for factor (min/max)     =          0.5598
     ratio of allocated memory (max/min)     =          1.2060
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.015625        0.017214
     time (cpu & wall) for ordering          =        0.109375        0.104811
     time (cpu & wall) for other matrix prep =        0.015625        0.014348
     time (cpu & wall) for value input       =        0.046875        0.042396
     time (cpu & wall) for matrix distrib.   =        0.140625        0.128175
     time (cpu & wall) for numeric factor    =        0.171875        0.169851
     computational rate (gflops) for factor  =       21.502446       21.758651
     time (cpu & wall) for numeric solve     =        0.015625        0.013445
     computational rate (gflops) for solve   =       11.932561       13.866919
     effective I/O rate (GB/sec) for solve   =       44.455783       51.662398

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        294912.        2. MB        263304.        2. MB
                95-   1        262144.        2. MB        230037.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        557056.        4. MB        493341.        4. MB


  Solver Memory allocated on core    0       =      144.387 MB
  Solver Memory allocated on core    1       =      119.723 MB
  Total Solver Memory allocated by all cores =      264.110 MB





  Performance statistics for DSP solver: icalls =     11

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2081032
     no. of nonzeroes in the factor l        =        12577181
     ratio of nonzeroes in factor (min/max)  =          0.7530
     number of super nodes                   =            1966
     maximum order of a front matrix         =             849
     maximum size of a front matrix          =          360825
     maximum size of a front trapezoid       =          282975
     no. of floating point ops for factor    =      3.6957D+09
     no. of floating point ops for solve     =      1.8645D+08
     ratio of flops for factor (min/max)     =          0.5598
     ratio of allocated memory (max/min)     =          1.2060
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.020022
     time (cpu & wall) for matrix distrib.   =        0.078125        0.065570
     time (cpu & wall) for numeric factor    =        0.171875        0.171748
     computational rate (gflops) for factor  =       21.502446       21.518384
     time (cpu & wall) for numeric solve     =        0.015625        0.016937
     computational rate (gflops) for solve   =       11.932561       11.008158
     effective I/O rate (GB/sec) for solve   =       44.455783       41.011838

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        294912.        2. MB        263304.        2. MB
                95-   1        262144.        2. MB        230037.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        557056.        4. MB        493341.        4. MB


  Solver Memory allocated on core    0       =      144.387 MB
  Solver Memory allocated on core    1       =      119.723 MB
  Total Solver Memory allocated by all cores =      264.110 MB





  Performance statistics for DSP solver: icalls =     12

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2081032
     no. of nonzeroes in the factor l        =        12577181
     ratio of nonzeroes in factor (min/max)  =          0.7530
     number of super nodes                   =            1966
     maximum order of a front matrix         =             849
     maximum size of a front matrix          =          360825
     maximum size of a front trapezoid       =          282975
     no. of floating point ops for factor    =      3.6957D+09
     no. of floating point ops for solve     =      1.8645D+08
     ratio of flops for factor (min/max)     =          0.5598
     ratio of allocated memory (max/min)     =          1.2060
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.031250        0.032369
     time (cpu & wall) for matrix distrib.   =        0.078125        0.073450
     time (cpu & wall) for numeric factor    =        0.171875        0.182453
     computational rate (gflops) for factor  =       21.502446       20.255797
     time (cpu & wall) for numeric solve     =        0.015625        0.015853
     computational rate (gflops) for solve   =       11.932561       11.760797
     effective I/O rate (GB/sec) for solve   =       44.455783       43.815861

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        294912.        2. MB        263304.        2. MB
                95-   1        262144.        2. MB        230037.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        557056.        4. MB        493341.        4. MB


  Solver Memory allocated on core    0       =      144.387 MB
  Solver Memory allocated on core    1       =      119.723 MB
  Total Solver Memory allocated by all cores =      264.110 MB





  Performance statistics for DSP solver: icalls =     13

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2081032
     no. of nonzeroes in the factor l        =        12577181
     ratio of nonzeroes in factor (min/max)  =          0.7530
     number of super nodes                   =            1966
     maximum order of a front matrix         =             849
     maximum size of a front matrix          =          360825
     maximum size of a front trapezoid       =          282975
     no. of floating point ops for factor    =      3.6957D+09
     no. of floating point ops for solve     =      1.8645D+08
     ratio of flops for factor (min/max)     =          0.5598
     ratio of allocated memory (max/min)     =          1.2060
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.031250        0.023137
     time (cpu & wall) for matrix distrib.   =        0.078125        0.069979
     time (cpu & wall) for numeric factor    =        0.171875        0.176630
     computational rate (gflops) for factor  =       21.502446       20.923574
     time (cpu & wall) for numeric solve     =        0.015625        0.014304
     computational rate (gflops) for solve   =       11.932561       13.034463
     effective I/O rate (GB/sec) for solve   =       44.455783       48.561014

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        294912.        2. MB        263304.        2. MB
                95-   1        262144.        2. MB        230037.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        557056.        4. MB        493341.        4. MB


  Solver Memory allocated on core    0       =      144.387 MB
  Solver Memory allocated on core    1       =      119.723 MB
  Total Solver Memory allocated by all cores =      264.110 MB





  Performance statistics for DSP solver: icalls =     14

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2081518
     no. of nonzeroes in the factor l        =        12617205
     ratio of nonzeroes in factor (min/max)  =          0.7715
     number of super nodes                   =            1962
     maximum order of a front matrix         =             858
     maximum size of a front matrix          =          368511
     maximum size of a front trapezoid       =          319683
     no. of floating point ops for factor    =      3.6527D+09
     no. of floating point ops for solve     =      2.3349D+08
     ratio of flops for factor (min/max)     =          0.5932
     ratio of allocated memory (max/min)     =          1.1728
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.015625        0.014268
     time (cpu & wall) for ordering          =        0.171875        0.174298
     time (cpu & wall) for other matrix prep =        0.015625        0.018872
     time (cpu & wall) for value input       =        0.062500        0.090686
     time (cpu & wall) for matrix distrib.   =        0.171875        0.174938
     time (cpu & wall) for numeric factor    =        0.203125        0.219289
     computational rate (gflops) for factor  =       17.982521       16.657004

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        294912.        2. MB        262515.        2. MB
                95-   1        262144.        2. MB        230419.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        557056.        4. MB        492934.        4. MB


  Solver Memory allocated on core    0       =      141.441 MB
  Solver Memory allocated on core    1       =      120.596 MB
  Total Solver Memory allocated by all cores =      262.037 MB





  Performance statistics for DSP solver: icalls =     15

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2081518
     no. of nonzeroes in the factor l        =        12617205
     ratio of nonzeroes in factor (min/max)  =          0.7715
     number of super nodes                   =            1962
     maximum order of a front matrix         =             858
     maximum size of a front matrix          =          368511
     maximum size of a front trapezoid       =          319683
     no. of floating point ops for factor    =      3.6527D+09
     no. of floating point ops for solve     =      2.3349D+08
     ratio of flops for factor (min/max)     =          0.5932
     ratio of allocated memory (max/min)     =          1.1728
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.031250        0.035175
     time (cpu & wall) for matrix distrib.   =        0.109375        0.108625
     time (cpu & wall) for numeric factor    =        0.203125        0.236730
     computational rate (gflops) for factor  =       17.982521       15.429819
     time (cpu & wall) for numeric solve     =        0.015625        0.013942
     computational rate (gflops) for solve   =       14.943269       16.747377
     effective I/O rate (GB/sec) for solve   =       55.672435       62.393794

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        294912.        2. MB        262515.        2. MB
                95-   1        262144.        2. MB        230419.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        557056.        4. MB        492934.        4. MB


  Solver Memory allocated on core    0       =      141.441 MB
  Solver Memory allocated on core    1       =      120.596 MB
  Total Solver Memory allocated by all cores =      262.037 MB





  Performance statistics for DSP solver: icalls =     16

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2081518
     no. of nonzeroes in the factor l        =        12617205
     ratio of nonzeroes in factor (min/max)  =          0.7715
     number of super nodes                   =            1962
     maximum order of a front matrix         =             858
     maximum size of a front matrix          =          368511
     maximum size of a front trapezoid       =          319683
     no. of floating point ops for factor    =      3.6527D+09
     no. of floating point ops for solve     =      2.3349D+08
     ratio of flops for factor (min/max)     =          0.5932
     ratio of allocated memory (max/min)     =          1.1728
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.031250        0.027714
     time (cpu & wall) for matrix distrib.   =        0.093750        0.114093
     time (cpu & wall) for numeric factor    =        0.250000        0.275704
     computational rate (gflops) for factor  =       14.610798       13.248613
     time (cpu & wall) for numeric solve     =        0.015625        0.016602
     computational rate (gflops) for solve   =       14.943269       14.063713
     effective I/O rate (GB/sec) for solve   =       55.672435       52.395574

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        294912.        2. MB        262515.        2. MB
                95-   1        262144.        2. MB        230419.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        557056.        4. MB        492934.        4. MB


  Solver Memory allocated on core    0       =      141.441 MB
  Solver Memory allocated on core    1       =      120.596 MB
  Total Solver Memory allocated by all cores =      262.037 MB





  Performance statistics for DSP solver: icalls =     17

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2081518
     no. of nonzeroes in the factor l        =        12617205
     ratio of nonzeroes in factor (min/max)  =          0.7715
     number of super nodes                   =            1962
     maximum order of a front matrix         =             858
     maximum size of a front matrix          =          368511
     maximum size of a front trapezoid       =          319683
     no. of floating point ops for factor    =      3.6527D+09
     no. of floating point ops for solve     =      2.3349D+08
     ratio of flops for factor (min/max)     =          0.5932
     ratio of allocated memory (max/min)     =          1.1728
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.027259
     time (cpu & wall) for matrix distrib.   =        0.078125        0.085912
     time (cpu & wall) for numeric factor    =        0.250000        0.309807
     computational rate (gflops) for factor  =       14.610798       11.790257
     time (cpu & wall) for numeric solve     =        0.015625        0.012831
     computational rate (gflops) for solve   =       14.943269       18.196657
     effective I/O rate (GB/sec) for solve   =       55.672435       67.793210

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        294912.        2. MB        262515.        2. MB
                95-   1        262144.        2. MB        230419.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        557056.        4. MB        492934.        4. MB


  Solver Memory allocated on core    0       =      141.441 MB
  Solver Memory allocated on core    1       =      120.596 MB
  Total Solver Memory allocated by all cores =      262.037 MB





  Performance statistics for DSP solver: icalls =     18

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2081518
     no. of nonzeroes in the factor l        =        12617205
     ratio of nonzeroes in factor (min/max)  =          0.7715
     number of super nodes                   =            1962
     maximum order of a front matrix         =             858
     maximum size of a front matrix          =          368511
     maximum size of a front trapezoid       =          319683
     no. of floating point ops for factor    =      3.6527D+09
     no. of floating point ops for solve     =      2.3349D+08
     ratio of flops for factor (min/max)     =          0.5932
     ratio of allocated memory (max/min)     =          1.1728
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.020637
     time (cpu & wall) for matrix distrib.   =        0.062500        0.075953
     time (cpu & wall) for numeric factor    =        0.171875        0.198896
     computational rate (gflops) for factor  =       21.252070       18.364862
     time (cpu & wall) for numeric solve     =        0.031250        0.025217
     computational rate (gflops) for solve   =        7.471635        9.259064
     effective I/O rate (GB/sec) for solve   =       27.836218       34.495438

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        294912.        2. MB        262515.        2. MB
                95-   1        262144.        2. MB        230419.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        557056.        4. MB        492934.        4. MB


  Solver Memory allocated on core    0       =      141.441 MB
  Solver Memory allocated on core    1       =      120.596 MB
  Total Solver Memory allocated by all cores =      262.037 MB





  Performance statistics for DSP solver: icalls =     19

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2081518
     no. of nonzeroes in the factor l        =        12617205
     ratio of nonzeroes in factor (min/max)  =          0.7715
     number of super nodes                   =            1962
     maximum order of a front matrix         =             858
     maximum size of a front matrix          =          368511
     maximum size of a front trapezoid       =          319683
     no. of floating point ops for factor    =      3.6527D+09
     no. of floating point ops for solve     =      2.3349D+08
     ratio of flops for factor (min/max)     =          0.5932
     ratio of allocated memory (max/min)     =          1.1728
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.020575
     time (cpu & wall) for matrix distrib.   =        0.078125        0.074568
     time (cpu & wall) for numeric factor    =        0.203125        0.224531
     computational rate (gflops) for factor  =       17.982521       16.268130
     time (cpu & wall) for numeric solve     =        0.015625        0.014398
     computational rate (gflops) for solve   =       14.943269       16.216512
     effective I/O rate (GB/sec) for solve   =       55.672435       60.416010

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        294912.        2. MB        262515.        2. MB
                95-   1        262144.        2. MB        230419.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        557056.        4. MB        492934.        4. MB


  Solver Memory allocated on core    0       =      141.441 MB
  Solver Memory allocated on core    1       =      120.596 MB
  Total Solver Memory allocated by all cores =      262.037 MB





  Performance statistics for DSP solver: icalls =     20

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2081518
     no. of nonzeroes in the factor l        =        12617205
     ratio of nonzeroes in factor (min/max)  =          0.7715
     number of super nodes                   =            1962
     maximum order of a front matrix         =             858
     maximum size of a front matrix          =          368511
     maximum size of a front trapezoid       =          319683
     no. of floating point ops for factor    =      3.6527D+09
     no. of floating point ops for solve     =      2.3349D+08
     ratio of flops for factor (min/max)     =          0.5932
     ratio of allocated memory (max/min)     =          1.1728
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.018985
     time (cpu & wall) for matrix distrib.   =        0.078125        0.079835
     time (cpu & wall) for numeric factor    =        0.218750        0.232604
     computational rate (gflops) for factor  =       16.698055       15.703511
     time (cpu & wall) for numeric solve     =        0.015625        0.021462
     computational rate (gflops) for solve   =       14.943269       10.879112
     effective I/O rate (GB/sec) for solve   =       55.672435       40.531066

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        294912.        2. MB        262515.        2. MB
                95-   1        262144.        2. MB        230419.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        557056.        4. MB        492934.        4. MB


  Solver Memory allocated on core    0       =      141.441 MB
  Solver Memory allocated on core    1       =      120.596 MB
  Total Solver Memory allocated by all cores =      262.037 MB





  Performance statistics for DSP solver: icalls =     21

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2081518
     no. of nonzeroes in the factor l        =        12617205
     ratio of nonzeroes in factor (min/max)  =          0.7715
     number of super nodes                   =            1962
     maximum order of a front matrix         =             858
     maximum size of a front matrix          =          368511
     maximum size of a front trapezoid       =          319683
     no. of floating point ops for factor    =      3.6527D+09
     no. of floating point ops for solve     =      2.3349D+08
     ratio of flops for factor (min/max)     =          0.5932
     ratio of allocated memory (max/min)     =          1.1728
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.019624
     time (cpu & wall) for matrix distrib.   =        0.062500        0.082472
     time (cpu & wall) for numeric factor    =        0.171875        0.177004
     computational rate (gflops) for factor  =       21.252070       20.636231
     time (cpu & wall) for numeric solve     =        0.015625        0.014243
     computational rate (gflops) for solve   =       14.943269       16.393217
     effective I/O rate (GB/sec) for solve   =       55.672435       61.074338

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        294912.        2. MB        262515.        2. MB
                95-   1        262144.        2. MB        230419.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        557056.        4. MB        492934.        4. MB


  Solver Memory allocated on core    0       =      141.441 MB
  Solver Memory allocated on core    1       =      120.596 MB
  Total Solver Memory allocated by all cores =      262.037 MB





  Performance statistics for DSP solver: icalls =     22

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2081518
     no. of nonzeroes in the factor l        =        12617205
     ratio of nonzeroes in factor (min/max)  =          0.7715
     number of super nodes                   =            1962
     maximum order of a front matrix         =             858
     maximum size of a front matrix          =          368511
     maximum size of a front trapezoid       =          319683
     no. of floating point ops for factor    =      3.6527D+09
     no. of floating point ops for solve     =      2.3349D+08
     ratio of flops for factor (min/max)     =          0.5932
     ratio of allocated memory (max/min)     =          1.1728
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.035265
     time (cpu & wall) for matrix distrib.   =        0.078125        0.074106
     time (cpu & wall) for numeric factor    =        0.218750        0.250450
     computational rate (gflops) for factor  =       16.698055       14.584528
     time (cpu & wall) for numeric solve     =        0.015625        0.020572
     computational rate (gflops) for solve   =       14.943269       11.350100
     effective I/O rate (GB/sec) for solve   =       55.672435       42.285774

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        294912.        2. MB        262515.        2. MB
                95-   1        262144.        2. MB        230419.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        557056.        4. MB        492934.        4. MB


  Solver Memory allocated on core    0       =      141.441 MB
  Solver Memory allocated on core    1       =      120.596 MB
  Total Solver Memory allocated by all cores =      262.037 MB





  Performance statistics for DSP solver: icalls =     23

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2081518
     no. of nonzeroes in the factor l        =        12617205
     ratio of nonzeroes in factor (min/max)  =          0.7715
     number of super nodes                   =            1962
     maximum order of a front matrix         =             858
     maximum size of a front matrix          =          368511
     maximum size of a front trapezoid       =          319683
     no. of floating point ops for factor    =      3.6527D+09
     no. of floating point ops for solve     =      2.3349D+08
     ratio of flops for factor (min/max)     =          0.5932
     ratio of allocated memory (max/min)     =          1.1728
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.024670
     time (cpu & wall) for matrix distrib.   =        0.078125        0.074101
     time (cpu & wall) for numeric factor    =        0.171875        0.167916
     computational rate (gflops) for factor  =       21.252070       21.753123
     time (cpu & wall) for numeric solve     =        0.015625        0.012889
     computational rate (gflops) for solve   =       14.943269       18.115478
     effective I/O rate (GB/sec) for solve   =       55.672435       67.490771

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        294912.        2. MB        262515.        2. MB
                95-   1        262144.        2. MB        230419.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        557056.        4. MB        492934.        4. MB


  Solver Memory allocated on core    0       =      141.441 MB
  Solver Memory allocated on core    1       =      120.596 MB
  Total Solver Memory allocated by all cores =      262.037 MB





  Performance statistics for DSP solver: icalls =     24

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2081518
     no. of nonzeroes in the factor l        =        12617205
     ratio of nonzeroes in factor (min/max)  =          0.7715
     number of super nodes                   =            1962
     maximum order of a front matrix         =             858
     maximum size of a front matrix          =          368511
     maximum size of a front trapezoid       =          319683
     no. of floating point ops for factor    =      3.6527D+09
     no. of floating point ops for solve     =      2.3349D+08
     ratio of flops for factor (min/max)     =          0.5932
     ratio of allocated memory (max/min)     =          1.1728
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.031250        0.024100
     time (cpu & wall) for matrix distrib.   =        0.062500        0.065621
     time (cpu & wall) for numeric factor    =        0.171875        0.167889
     computational rate (gflops) for factor  =       21.252070       21.756595
     time (cpu & wall) for numeric solve     =        0.015625        0.014031
     computational rate (gflops) for solve   =       14.943269       16.641145
     effective I/O rate (GB/sec) for solve   =       55.672435       61.998019

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        294912.        2. MB        262515.        2. MB
                95-   1        262144.        2. MB        230419.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        557056.        4. MB        492934.        4. MB


  Solver Memory allocated on core    0       =      141.441 MB
  Solver Memory allocated on core    1       =      120.596 MB
  Total Solver Memory allocated by all cores =      262.037 MB





  Performance statistics for DSP solver: icalls =     25

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2081518
     no. of nonzeroes in the factor l        =        12617205
     ratio of nonzeroes in factor (min/max)  =          0.7715
     number of super nodes                   =            1962
     maximum order of a front matrix         =             858
     maximum size of a front matrix          =          368511
     maximum size of a front trapezoid       =          319683
     no. of floating point ops for factor    =      3.6527D+09
     no. of floating point ops for solve     =      2.3349D+08
     ratio of flops for factor (min/max)     =          0.5932
     ratio of allocated memory (max/min)     =          1.1728
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.020291
     time (cpu & wall) for matrix distrib.   =        0.078125        0.063815
     time (cpu & wall) for numeric factor    =        0.156250        0.167888
     computational rate (gflops) for factor  =       23.377277       21.756789
     time (cpu & wall) for numeric solve     =        0.015625        0.014669
     computational rate (gflops) for solve   =       14.943269       15.917578
     effective I/O rate (GB/sec) for solve   =       55.672435       59.302305

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        294912.        2. MB        262515.        2. MB
                95-   1        262144.        2. MB        230419.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        557056.        4. MB        492934.        4. MB


  Solver Memory allocated on core    0       =      141.441 MB
  Solver Memory allocated on core    1       =      120.596 MB
  Total Solver Memory allocated by all cores =      262.037 MB





  Performance statistics for DSP solver: icalls =     26

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2081518
     no. of nonzeroes in the factor l        =        12617205
     ratio of nonzeroes in factor (min/max)  =          0.7715
     number of super nodes                   =            1962
     maximum order of a front matrix         =             858
     maximum size of a front matrix          =          368511
     maximum size of a front trapezoid       =          319683
     no. of floating point ops for factor    =      3.6527D+09
     no. of floating point ops for solve     =      2.3349D+08
     ratio of flops for factor (min/max)     =          0.5932
     ratio of allocated memory (max/min)     =          1.1728
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.031250        0.021254
     time (cpu & wall) for matrix distrib.   =        0.046875        0.065713
     time (cpu & wall) for numeric factor    =        0.156250        0.167214
     computational rate (gflops) for factor  =       23.377277       21.844473
     time (cpu & wall) for numeric solve     =        0.015625        0.014973
     computational rate (gflops) for solve   =       14.943269       15.594287
     effective I/O rate (GB/sec) for solve   =       55.672435       58.097858

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        294912.        2. MB        262515.        2. MB
                95-   1        262144.        2. MB        230419.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        557056.        4. MB        492934.        4. MB


  Solver Memory allocated on core    0       =      141.441 MB
  Solver Memory allocated on core    1       =      120.596 MB
  Total Solver Memory allocated by all cores =      262.037 MB





  Performance statistics for DSP solver: icalls =     27

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2081518
     no. of nonzeroes in the factor l        =        12617205
     ratio of nonzeroes in factor (min/max)  =          0.7715
     number of super nodes                   =            1962
     maximum order of a front matrix         =             858
     maximum size of a front matrix          =          368511
     maximum size of a front trapezoid       =          319683
     no. of floating point ops for factor    =      3.6527D+09
     no. of floating point ops for solve     =      2.3349D+08
     ratio of flops for factor (min/max)     =          0.5932
     ratio of allocated memory (max/min)     =          1.1728
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.046875        0.051217
     time (cpu & wall) for matrix distrib.   =        0.062500        0.077442
     time (cpu & wall) for numeric factor    =        0.171875        0.165706
     computational rate (gflops) for factor  =       21.252070       22.043188
     time (cpu & wall) for numeric solve     =        0.015625        0.013278
     computational rate (gflops) for solve   =       14.943269       17.584885
     effective I/O rate (GB/sec) for solve   =       55.672435       65.514001

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        294912.        2. MB        262515.        2. MB
                95-   1        262144.        2. MB        230419.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        557056.        4. MB        492934.        4. MB


  Solver Memory allocated on core    0       =      141.441 MB
  Solver Memory allocated on core    1       =      120.596 MB
  Total Solver Memory allocated by all cores =      262.037 MB





  Performance statistics for DSP solver: icalls =     28

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2081518
     no. of nonzeroes in the factor l        =        12617205
     ratio of nonzeroes in factor (min/max)  =          0.7715
     number of super nodes                   =            1962
     maximum order of a front matrix         =             858
     maximum size of a front matrix          =          368511
     maximum size of a front trapezoid       =          319683
     no. of floating point ops for factor    =      3.6527D+09
     no. of floating point ops for solve     =      2.3349D+08
     ratio of flops for factor (min/max)     =          0.5932
     ratio of allocated memory (max/min)     =          1.1728
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.031250        0.021286
     time (cpu & wall) for matrix distrib.   =        0.078125        0.085744
     time (cpu & wall) for numeric factor    =        0.218750        0.223553
     computational rate (gflops) for factor  =       16.698055       16.339293
     time (cpu & wall) for numeric solve     =        0.015625        0.016565
     computational rate (gflops) for solve   =       14.943269       14.095211
     effective I/O rate (GB/sec) for solve   =       55.672435       52.512922

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        294912.        2. MB        262515.        2. MB
                95-   1        262144.        2. MB        230419.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        557056.        4. MB        492934.        4. MB


  Solver Memory allocated on core    0       =      141.441 MB
  Solver Memory allocated on core    1       =      120.596 MB
  Total Solver Memory allocated by all cores =      262.037 MB





  Performance statistics for DSP solver: icalls =     29

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2082490
     no. of nonzeroes in the factor l        =        12511199
     ratio of nonzeroes in factor (min/max)  =          0.8172
     number of super nodes                   =            1960
     maximum order of a front matrix         =             795
     maximum size of a front matrix          =          316410
     maximum size of a front trapezoid       =          245865
     no. of floating point ops for factor    =      3.5406D+09
     no. of floating point ops for solve     =      2.8011D+08
     ratio of flops for factor (min/max)     =          0.6622
     ratio of allocated memory (max/min)     =          1.1343
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.031250        0.016508
     time (cpu & wall) for ordering          =        0.109375        0.129596
     time (cpu & wall) for other matrix prep =        0.015625        0.012536
     time (cpu & wall) for value input       =        0.031250        0.040872
     time (cpu & wall) for matrix distrib.   =        0.140625        0.136559
     time (cpu & wall) for numeric factor    =        0.203125        0.193533
     computational rate (gflops) for factor  =       17.430434       18.294312
     time (cpu & wall) for numeric solve     =        0.015625        0.022984
     computational rate (gflops) for solve   =       17.927014       12.187368
     effective I/O rate (GB/sec) for solve   =       66.788632       45.405088

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        258874.        2. MB
                95-   1        262144.        2. MB        233710.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        524288.        4. MB        492584.        4. MB


  Solver Memory allocated on core    0       =      139.493 MB
  Solver Memory allocated on core    1       =      122.982 MB
  Total Solver Memory allocated by all cores =      262.475 MB





  Performance statistics for DSP solver: icalls =     30

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2082490
     no. of nonzeroes in the factor l        =        12511199
     ratio of nonzeroes in factor (min/max)  =          0.8172
     number of super nodes                   =            1960
     maximum order of a front matrix         =             795
     maximum size of a front matrix          =          316410
     maximum size of a front trapezoid       =          245865
     no. of floating point ops for factor    =      3.5406D+09
     no. of floating point ops for solve     =      2.8011D+08
     ratio of flops for factor (min/max)     =          0.6622
     ratio of allocated memory (max/min)     =          1.1343
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.006386
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.031250        0.020717
     time (cpu & wall) for matrix distrib.   =        0.062500        0.067692
     time (cpu & wall) for numeric factor    =        0.218750        0.234118
     computational rate (gflops) for factor  =       16.185403       15.122952
     time (cpu & wall) for numeric solve     =        0.015625        0.012222
     computational rate (gflops) for solve   =       17.927014       22.918662
     effective I/O rate (GB/sec) for solve   =       66.788632       85.385445

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        258874.        2. MB
                95-   1        262144.        2. MB        233710.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        524288.        4. MB        492584.        4. MB


  Solver Memory allocated on core    0       =      139.493 MB
  Solver Memory allocated on core    1       =      122.982 MB
  Total Solver Memory allocated by all cores =      262.474 MB





  Performance statistics for DSP solver: icalls =     31

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2082490
     no. of nonzeroes in the factor l        =        12511199
     ratio of nonzeroes in factor (min/max)  =          0.8172
     number of super nodes                   =            1960
     maximum order of a front matrix         =             795
     maximum size of a front matrix          =          316410
     maximum size of a front trapezoid       =          245865
     no. of floating point ops for factor    =      3.5406D+09
     no. of floating point ops for solve     =      2.8011D+08
     ratio of flops for factor (min/max)     =          0.6622
     ratio of allocated memory (max/min)     =          1.1343
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.031250        0.021832
     time (cpu & wall) for matrix distrib.   =        0.078125        0.075157
     time (cpu & wall) for numeric factor    =        0.187500        0.195708
     computational rate (gflops) for factor  =       18.882970       18.091054

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        258874.        2. MB
                95-   1        262144.        2. MB        233710.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        524288.        4. MB        492584.        4. MB


  Solver Memory allocated on core    0       =      139.493 MB
  Solver Memory allocated on core    1       =      122.982 MB
  Total Solver Memory allocated by all cores =      262.474 MB





  Performance statistics for DSP solver: icalls =     32

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2082787
     no. of nonzeroes in the factor l        =        12627840
     ratio of nonzeroes in factor (min/max)  =          0.8032
     number of super nodes                   =            1959
     maximum order of a front matrix         =             936
     maximum size of a front matrix          =          438516
     maximum size of a front trapezoid       =          356643
     no. of floating point ops for factor    =      3.7596D+09
     no. of floating point ops for solve     =      3.2720D+08
     ratio of flops for factor (min/max)     =          0.6236
     ratio of allocated memory (max/min)     =          1.1347
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.015625        0.012171
     time (cpu & wall) for ordering          =        0.125000        0.133528
     time (cpu & wall) for other matrix prep =        0.031250        0.022499
     time (cpu & wall) for value input       =        0.062500        0.063741
     time (cpu & wall) for matrix distrib.   =        0.203125        0.181822
     time (cpu & wall) for numeric factor    =        0.125000        0.163255
     computational rate (gflops) for factor  =       30.077089       23.029282
     time (cpu & wall) for numeric solve     =        0.031250        0.027218
     computational rate (gflops) for solve   =       10.470385       12.021616
     effective I/O rate (GB/sec) for solve   =       39.008320       44.787564

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        260560.        2. MB
                95-   1        262144.        2. MB        231801.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        524288.        4. MB        492361.        4. MB


  Solver Memory allocated on core    0       =      139.901 MB
  Solver Memory allocated on core    1       =      123.299 MB
  Total Solver Memory allocated by all cores =      263.200 MB





  Performance statistics for DSP solver: icalls =     33

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2082787
     no. of nonzeroes in the factor l        =        12627840
     ratio of nonzeroes in factor (min/max)  =          0.8032
     number of super nodes                   =            1959
     maximum order of a front matrix         =             936
     maximum size of a front matrix          =          438516
     maximum size of a front trapezoid       =          356643
     no. of floating point ops for factor    =      3.7596D+09
     no. of floating point ops for solve     =      3.2720D+08
     ratio of flops for factor (min/max)     =          0.6236
     ratio of allocated memory (max/min)     =          1.1347
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.024788
     time (cpu & wall) for matrix distrib.   =        0.062500        0.077941
     time (cpu & wall) for numeric factor    =        0.171875        0.173429
     computational rate (gflops) for factor  =       21.874247       21.678181
     time (cpu & wall) for numeric solve     =        0.015625        0.015937
     computational rate (gflops) for solve   =       20.940770       20.530682
     effective I/O rate (GB/sec) for solve   =       78.016641       76.488822

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        260560.        2. MB
                95-   1        262144.        2. MB        231801.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        524288.        4. MB        492361.        4. MB


  Solver Memory allocated on core    0       =      139.901 MB
  Solver Memory allocated on core    1       =      123.299 MB
  Total Solver Memory allocated by all cores =      263.200 MB





  Performance statistics for DSP solver: icalls =     34

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2082787
     no. of nonzeroes in the factor l        =        12627840
     ratio of nonzeroes in factor (min/max)  =          0.8032
     number of super nodes                   =            1959
     maximum order of a front matrix         =             936
     maximum size of a front matrix          =          438516
     maximum size of a front trapezoid       =          356643
     no. of floating point ops for factor    =      3.7596D+09
     no. of floating point ops for solve     =      3.2720D+08
     ratio of flops for factor (min/max)     =          0.6236
     ratio of allocated memory (max/min)     =          1.1347
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.031250        0.045054
     time (cpu & wall) for matrix distrib.   =        0.078125        0.087681
     time (cpu & wall) for numeric factor    =        0.218750        0.305924
     computational rate (gflops) for factor  =       17.186908       12.289429
     time (cpu & wall) for numeric solve     =        0.015625        0.029689
     computational rate (gflops) for solve   =       20.940770       11.020864
     effective I/O rate (GB/sec) for solve   =       78.016641       41.059177

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        260560.        2. MB
                95-   1        262144.        2. MB        231801.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        524288.        4. MB        492361.        4. MB


  Solver Memory allocated on core    0       =      139.901 MB
  Solver Memory allocated on core    1       =      123.299 MB
  Total Solver Memory allocated by all cores =      263.200 MB





  Performance statistics for DSP solver: icalls =     35

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2082787
     no. of nonzeroes in the factor l        =        12627840
     ratio of nonzeroes in factor (min/max)  =          0.8032
     number of super nodes                   =            1959
     maximum order of a front matrix         =             936
     maximum size of a front matrix          =          438516
     maximum size of a front trapezoid       =          356643
     no. of floating point ops for factor    =      3.7596D+09
     no. of floating point ops for solve     =      3.2720D+08
     ratio of flops for factor (min/max)     =          0.6236
     ratio of allocated memory (max/min)     =          1.1347
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.020930
     time (cpu & wall) for matrix distrib.   =        0.062500        0.064907
     time (cpu & wall) for numeric factor    =        0.203125        0.220363
     computational rate (gflops) for factor  =       18.508978       17.061120
     time (cpu & wall) for numeric solve     =        0.015625        0.023842
     computational rate (gflops) for solve   =       20.940770       13.723489
     effective I/O rate (GB/sec) for solve   =       78.016641       51.128037

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        260560.        2. MB
                95-   1        262144.        2. MB        231801.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        524288.        4. MB        492361.        4. MB


  Solver Memory allocated on core    0       =      139.901 MB
  Solver Memory allocated on core    1       =      123.299 MB
  Total Solver Memory allocated by all cores =      263.200 MB





  Performance statistics for DSP solver: icalls =     36

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2083273
     no. of nonzeroes in the factor l        =        12382746
     ratio of nonzeroes in factor (min/max)  =          0.8291
     number of super nodes                   =            1974
     maximum order of a front matrix         =             789
     maximum size of a front matrix          =          311655
     maximum size of a front trapezoid       =          252390
     no. of floating point ops for factor    =      3.4826D+09
     no. of floating point ops for solve     =      3.7329D+08
     ratio of flops for factor (min/max)     =          0.6775
     ratio of allocated memory (max/min)     =          1.1088
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.031250        0.016851
     time (cpu & wall) for ordering          =        0.109375        0.105761
     time (cpu & wall) for other matrix prep =        0.000000        0.012500
     time (cpu & wall) for value input       =        0.031250        0.046427
     time (cpu & wall) for matrix distrib.   =        0.140625        0.147894
     time (cpu & wall) for numeric factor    =        0.156250        0.154384
     computational rate (gflops) for factor  =       22.288764       22.558134
     time (cpu & wall) for numeric solve     =        0.015625        0.013078
     computational rate (gflops) for solve   =       23.890298       28.542169
     effective I/O rate (GB/sec) for solve   =       89.005360      106.336306

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        256789.        2. MB
                95-   1        262144.        2. MB        237785.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        524288.        4. MB        494574.        4. MB


  Solver Memory allocated on core    0       =      137.084 MB
  Solver Memory allocated on core    1       =      123.635 MB
  Total Solver Memory allocated by all cores =      260.719 MB





  Performance statistics for DSP solver: icalls =     37

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2083273
     no. of nonzeroes in the factor l        =        12382746
     ratio of nonzeroes in factor (min/max)  =          0.8291
     number of super nodes                   =            1974
     maximum order of a front matrix         =             789
     maximum size of a front matrix          =          311655
     maximum size of a front trapezoid       =          252390
     no. of floating point ops for factor    =      3.4826D+09
     no. of floating point ops for solve     =      3.7329D+08
     ratio of flops for factor (min/max)     =          0.6775
     ratio of allocated memory (max/min)     =          1.1088
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.024446
     time (cpu & wall) for matrix distrib.   =        0.046875        0.064036
     time (cpu & wall) for numeric factor    =        0.156250        0.157554
     computational rate (gflops) for factor  =       22.288764       22.104248

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        256789.        2. MB
                95-   1        262144.        2. MB        237785.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        524288.        4. MB        494574.        4. MB


  Solver Memory allocated on core    0       =      137.084 MB
  Solver Memory allocated on core    1       =      123.635 MB
  Total Solver Memory allocated by all cores =      260.719 MB





  Performance statistics for DSP solver: icalls =     38

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2083516
     no. of nonzeroes in the factor l        =        12751209
     ratio of nonzeroes in factor (min/max)  =          0.8082
     number of super nodes                   =            1974
     maximum order of a front matrix         =             864
     maximum size of a front matrix          =          373680
     maximum size of a front trapezoid       =          328530
     no. of floating point ops for factor    =      3.7143D+09
     no. of floating point ops for solve     =      4.2083D+08
     ratio of flops for factor (min/max)     =          0.6558
     ratio of allocated memory (max/min)     =          1.1399
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.031250        0.017415
     time (cpu & wall) for ordering          =        0.109375        0.102337
     time (cpu & wall) for other matrix prep =        0.000000        0.012911
     time (cpu & wall) for value input       =        0.062500        0.041533
     time (cpu & wall) for matrix distrib.   =        0.109375        0.126982
     time (cpu & wall) for numeric factor    =        0.156250        0.159746
     computational rate (gflops) for factor  =       23.771391       23.251087
     time (cpu & wall) for numeric solve     =        0.015625        0.013312
     computational rate (gflops) for solve   =       26.933435       31.614388
     effective I/O rate (GB/sec) for solve   =      100.342829      117.782121

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        294912.        2. MB        263111.        2. MB
                95-   1        262144.        2. MB        231834.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        557056.        4. MB        494945.        4. MB


  Solver Memory allocated on core    0       =      140.663 MB
  Solver Memory allocated on core    1       =      123.405 MB
  Total Solver Memory allocated by all cores =      264.068 MB





  Performance statistics for DSP solver: icalls =     39

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2083516
     no. of nonzeroes in the factor l        =        12751209
     ratio of nonzeroes in factor (min/max)  =          0.8082
     number of super nodes                   =            1974
     maximum order of a front matrix         =             864
     maximum size of a front matrix          =          373680
     maximum size of a front trapezoid       =          328530
     no. of floating point ops for factor    =      3.7143D+09
     no. of floating point ops for solve     =      4.2083D+08
     ratio of flops for factor (min/max)     =          0.6558
     ratio of allocated memory (max/min)     =          1.1399
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.021844
     time (cpu & wall) for matrix distrib.   =        0.062500        0.065345
     time (cpu & wall) for numeric factor    =        0.171875        0.161434
     computational rate (gflops) for factor  =       21.610355       23.008039
     time (cpu & wall) for numeric solve     =        0.015625        0.013750
     computational rate (gflops) for solve   =       26.933435       30.606621
     effective I/O rate (GB/sec) for solve   =      100.342829      114.027600

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        294912.        2. MB        263111.        2. MB
                95-   1        262144.        2. MB        231834.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        557056.        4. MB        494945.        4. MB


  Solver Memory allocated on core    0       =      140.663 MB
  Solver Memory allocated on core    1       =      123.405 MB
  Total Solver Memory allocated by all cores =      264.068 MB





  Performance statistics for DSP solver: icalls =     40

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2083516
     no. of nonzeroes in the factor l        =        12751209
     ratio of nonzeroes in factor (min/max)  =          0.8082
     number of super nodes                   =            1974
     maximum order of a front matrix         =             864
     maximum size of a front matrix          =          373680
     maximum size of a front trapezoid       =          328530
     no. of floating point ops for factor    =      3.7143D+09
     no. of floating point ops for solve     =      4.2083D+08
     ratio of flops for factor (min/max)     =          0.6558
     ratio of allocated memory (max/min)     =          1.1399
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.031250        0.031140
     time (cpu & wall) for matrix distrib.   =        0.109375        0.124384
     time (cpu & wall) for numeric factor    =        0.218750        0.215838
     computational rate (gflops) for factor  =       16.979565       17.208654
     time (cpu & wall) for numeric solve     =        0.031250        0.020637
     computational rate (gflops) for solve   =       13.466718       20.392055
     effective I/O rate (GB/sec) for solve   =       50.171414       75.972356

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        294912.        2. MB        263111.        2. MB
                95-   1        262144.        2. MB        231834.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        557056.        4. MB        494945.        4. MB


  Solver Memory allocated on core    0       =      140.663 MB
  Solver Memory allocated on core    1       =      123.405 MB
  Total Solver Memory allocated by all cores =      264.068 MB





  Performance statistics for DSP solver: icalls =     41

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2083516
     no. of nonzeroes in the factor l        =        12751209
     ratio of nonzeroes in factor (min/max)  =          0.8082
     number of super nodes                   =            1974
     maximum order of a front matrix         =             864
     maximum size of a front matrix          =          373680
     maximum size of a front trapezoid       =          328530
     no. of floating point ops for factor    =      3.7143D+09
     no. of floating point ops for solve     =      4.2083D+08
     ratio of flops for factor (min/max)     =          0.6558
     ratio of allocated memory (max/min)     =          1.1399
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.031250        0.030287
     time (cpu & wall) for matrix distrib.   =        0.093750        0.090143
     time (cpu & wall) for numeric factor    =        0.187500        0.202811
     computational rate (gflops) for factor  =       19.809492       18.314032
     time (cpu & wall) for numeric solve     =        0.015625        0.016309
     computational rate (gflops) for solve   =       26.933435       25.804479
     effective I/O rate (GB/sec) for solve   =      100.342829       96.136805

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        294912.        2. MB        263111.        2. MB
                95-   1        262144.        2. MB        231834.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        557056.        4. MB        494945.        4. MB


  Solver Memory allocated on core    0       =      140.663 MB
  Solver Memory allocated on core    1       =      123.405 MB
  Total Solver Memory allocated by all cores =      264.068 MB





  Performance statistics for DSP solver: icalls =     42

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2084137
     no. of nonzeroes in the factor l        =        12846216
     ratio of nonzeroes in factor (min/max)  =          0.8247
     number of super nodes                   =            1950
     maximum order of a front matrix         =             861
     maximum size of a front matrix          =          371091
     maximum size of a front trapezoid       =          305448
     no. of floating point ops for factor    =      3.8608D+09
     no. of floating point ops for solve     =      4.6878D+08
     ratio of flops for factor (min/max)     =          0.6471
     ratio of allocated memory (max/min)     =          1.1351
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.015625        0.015340
     time (cpu & wall) for ordering          =        0.156250        0.191382
     time (cpu & wall) for other matrix prep =        0.015625        0.014514
     time (cpu & wall) for value input       =        0.046875        0.059446
     time (cpu & wall) for matrix distrib.   =        0.140625        0.163124
     time (cpu & wall) for numeric factor    =        0.156250        0.166045
     computational rate (gflops) for factor  =       24.708958       23.251333
     time (cpu & wall) for numeric solve     =        0.015625        0.015234
     computational rate (gflops) for solve   =       30.002029       30.772877
     effective I/O rate (GB/sec) for solve   =      111.775139      114.647001

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        258749.        2. MB
                95-   1        262144.        2. MB        233273.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        524288.        4. MB        492022.        4. MB


  Solver Memory allocated on core    0       =      142.059 MB
  Solver Memory allocated on core    1       =      125.149 MB
  Total Solver Memory allocated by all cores =      267.208 MB





  Performance statistics for DSP solver: icalls =     43

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2084137
     no. of nonzeroes in the factor l        =        12846216
     ratio of nonzeroes in factor (min/max)  =          0.8247
     number of super nodes                   =            1950
     maximum order of a front matrix         =             861
     maximum size of a front matrix          =          371091
     maximum size of a front trapezoid       =          305448
     no. of floating point ops for factor    =      3.8608D+09
     no. of floating point ops for solve     =      4.6878D+08
     ratio of flops for factor (min/max)     =          0.6471
     ratio of allocated memory (max/min)     =          1.1351
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.019810
     time (cpu & wall) for matrix distrib.   =        0.078125        0.083768
     time (cpu & wall) for numeric factor    =        0.203125        0.241680
     computational rate (gflops) for factor  =       19.006890       15.974758
     time (cpu & wall) for numeric solve     =        0.015625        0.027946
     computational rate (gflops) for solve   =       30.002029       16.774675
     effective I/O rate (GB/sec) for solve   =      111.775139       62.495493

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        258749.        2. MB
                95-   1        262144.        2. MB        233273.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        524288.        4. MB        492022.        4. MB


  Solver Memory allocated on core    0       =      142.059 MB
  Solver Memory allocated on core    1       =      125.149 MB
  Total Solver Memory allocated by all cores =      267.208 MB





  Performance statistics for DSP solver: icalls =     44

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2084137
     no. of nonzeroes in the factor l        =        12846216
     ratio of nonzeroes in factor (min/max)  =          0.8247
     number of super nodes                   =            1950
     maximum order of a front matrix         =             861
     maximum size of a front matrix          =          371091
     maximum size of a front trapezoid       =          305448
     no. of floating point ops for factor    =      3.8608D+09
     no. of floating point ops for solve     =      4.6878D+08
     ratio of flops for factor (min/max)     =          0.6471
     ratio of allocated memory (max/min)     =          1.1351
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.031250        0.020064
     time (cpu & wall) for matrix distrib.   =        0.046875        0.086965
     time (cpu & wall) for numeric factor    =        0.203125        0.262937
     computational rate (gflops) for factor  =       19.006890       14.683291
     time (cpu & wall) for numeric solve     =        0.046875        0.041938
     computational rate (gflops) for solve   =       10.000676       11.177863
     effective I/O rate (GB/sec) for solve   =       37.258380       41.644091

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        258749.        2. MB
                95-   1        262144.        2. MB        233273.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        524288.        4. MB        492022.        4. MB


  Solver Memory allocated on core    0       =      142.059 MB
  Solver Memory allocated on core    1       =      125.149 MB
  Total Solver Memory allocated by all cores =      267.208 MB





  Performance statistics for DSP solver: icalls =     45

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2084137
     no. of nonzeroes in the factor l        =        12846216
     ratio of nonzeroes in factor (min/max)  =          0.8247
     number of super nodes                   =            1950
     maximum order of a front matrix         =             861
     maximum size of a front matrix          =          371091
     maximum size of a front trapezoid       =          305448
     no. of floating point ops for factor    =      3.8608D+09
     no. of floating point ops for solve     =      4.6878D+08
     ratio of flops for factor (min/max)     =          0.6471
     ratio of allocated memory (max/min)     =          1.1351
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.015625        0.008262
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.021626
     time (cpu & wall) for matrix distrib.   =        0.062500        0.066076
     time (cpu & wall) for numeric factor    =        0.187500        0.209461
     computational rate (gflops) for factor  =       20.590798       18.431950
     time (cpu & wall) for numeric solve     =        0.015625        0.013615
     computational rate (gflops) for solve   =       30.002029       34.432279
     effective I/O rate (GB/sec) for solve   =      111.775139      128.280416

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        258749.        2. MB
                95-   1        262144.        2. MB        233273.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        524288.        4. MB        492022.        4. MB


  Solver Memory allocated on core    0       =      142.056 MB
  Solver Memory allocated on core    1       =      125.147 MB
  Total Solver Memory allocated by all cores =      267.203 MB





  Performance statistics for DSP solver: icalls =     46

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2084488
     no. of nonzeroes in the factor l        =        12934999
     ratio of nonzeroes in factor (min/max)  =          0.8284
     number of super nodes                   =            1970
     maximum order of a front matrix         =             921
     maximum size of a front matrix          =          424581
     maximum size of a front trapezoid       =          348336
     no. of floating point ops for factor    =      3.8907D+09
     no. of floating point ops for solve     =      5.1706D+08
     ratio of flops for factor (min/max)     =          0.6450
     ratio of allocated memory (max/min)     =          1.1376
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.015625        0.013822
     time (cpu & wall) for ordering          =        0.125000        0.149573
     time (cpu & wall) for other matrix prep =        0.000000        0.024250
     time (cpu & wall) for value input       =        0.031250        0.057723
     time (cpu & wall) for matrix distrib.   =        0.140625        0.155839
     time (cpu & wall) for numeric factor    =        0.234375        0.346053
     computational rate (gflops) for factor  =       16.600221       11.243005
     time (cpu & wall) for numeric solve     =        0.015625        0.012848
     computational rate (gflops) for solve   =       33.092108       40.245661
     effective I/O rate (GB/sec) for solve   =      123.287493      149.938672

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        258600.        2. MB
                95-   1        262144.        2. MB        235933.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        524288.        4. MB        494533.        4. MB


  Solver Memory allocated on core    0       =      143.220 MB
  Solver Memory allocated on core    1       =      125.901 MB
  Total Solver Memory allocated by all cores =      269.121 MB





  Performance statistics for DSP solver: icalls =     47

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2084488
     no. of nonzeroes in the factor l        =        12934999
     ratio of nonzeroes in factor (min/max)  =          0.8284
     number of super nodes                   =            1970
     maximum order of a front matrix         =             921
     maximum size of a front matrix          =          424581
     maximum size of a front trapezoid       =          348336
     no. of floating point ops for factor    =      3.8907D+09
     no. of floating point ops for solve     =      5.1706D+08
     ratio of flops for factor (min/max)     =          0.6450
     ratio of allocated memory (max/min)     =          1.1376
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.021184
     time (cpu & wall) for matrix distrib.   =        0.062500        0.106738
     time (cpu & wall) for numeric factor    =        0.234375        0.241110
     computational rate (gflops) for factor  =       16.600221       16.136515
     time (cpu & wall) for numeric solve     =        0.031250        0.024317
     computational rate (gflops) for solve   =       16.546054       21.263223
     effective I/O rate (GB/sec) for solve   =       61.643747       79.217968

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        258600.        2. MB
                95-   1        262144.        2. MB        235933.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        524288.        4. MB        494533.        4. MB


  Solver Memory allocated on core    0       =      143.220 MB
  Solver Memory allocated on core    1       =      125.901 MB
  Total Solver Memory allocated by all cores =      269.121 MB





  Performance statistics for DSP solver: icalls =     48

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2084488
     no. of nonzeroes in the factor l        =        12934999
     ratio of nonzeroes in factor (min/max)  =          0.8284
     number of super nodes                   =            1970
     maximum order of a front matrix         =             921
     maximum size of a front matrix          =          424581
     maximum size of a front trapezoid       =          348336
     no. of floating point ops for factor    =      3.8907D+09
     no. of floating point ops for solve     =      5.1706D+08
     ratio of flops for factor (min/max)     =          0.6450
     ratio of allocated memory (max/min)     =          1.1376
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.020876
     time (cpu & wall) for matrix distrib.   =        0.046875        0.081649
     time (cpu & wall) for numeric factor    =        0.203125        0.202695
     computational rate (gflops) for factor  =       19.154101       19.194763

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        258600.        2. MB
                95-   1        262144.        2. MB        235933.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        524288.        4. MB        494533.        4. MB


  Solver Memory allocated on core    0       =      143.220 MB
  Solver Memory allocated on core    1       =      125.901 MB
  Total Solver Memory allocated by all cores =      269.121 MB





  Performance statistics for DSP solver: icalls =     49

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2084488
     no. of nonzeroes in the factor l        =        12934999
     ratio of nonzeroes in factor (min/max)  =          0.8284
     number of super nodes                   =            1970
     maximum order of a front matrix         =             921
     maximum size of a front matrix          =          424581
     maximum size of a front trapezoid       =          348336
     no. of floating point ops for factor    =      3.8907D+09
     no. of floating point ops for solve     =      5.1706D+08
     ratio of flops for factor (min/max)     =          0.6450
     ratio of allocated memory (max/min)     =          1.1376
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.031250        0.031996
     time (cpu & wall) for matrix distrib.   =        0.078125        0.084087
     time (cpu & wall) for numeric factor    =        0.171875        0.163247
     computational rate (gflops) for factor  =       22.636664       23.833052
     time (cpu & wall) for numeric solve     =        0.015625        0.013139
     computational rate (gflops) for solve   =       33.092108       39.354588
     effective I/O rate (GB/sec) for solve   =      123.287493      146.618900

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        258600.        2. MB
                95-   1        262144.        2. MB        235933.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        524288.        4. MB        494533.        4. MB


  Solver Memory allocated on core    0       =      143.220 MB
  Solver Memory allocated on core    1       =      125.901 MB
  Total Solver Memory allocated by all cores =      269.121 MB





  Performance statistics for DSP solver: icalls =     50

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2084974
     no. of nonzeroes in the factor l        =        12859738
     ratio of nonzeroes in factor (min/max)  =          0.7890
     number of super nodes                   =            1973
     maximum order of a front matrix         =             918
     maximum size of a front matrix          =          421821
     maximum size of a front trapezoid       =          358986
     no. of floating point ops for factor    =      3.8787D+09
     no. of floating point ops for solve     =      5.6506D+08
     ratio of flops for factor (min/max)     =          0.5795
     ratio of allocated memory (max/min)     =          1.1651
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.015625        0.016619
     time (cpu & wall) for ordering          =        0.093750        0.109574
     time (cpu & wall) for other matrix prep =        0.015625        0.012926
     time (cpu & wall) for value input       =        0.046875        0.048249
     time (cpu & wall) for matrix distrib.   =        0.125000        0.133088
     time (cpu & wall) for numeric factor    =        0.171875        0.181381
     computational rate (gflops) for factor  =       22.566909       21.384164
     time (cpu & wall) for numeric solve     =        0.015625        0.019119
     computational rate (gflops) for solve   =       36.163939       29.554355
     effective I/O rate (GB/sec) for solve   =      134.731864      110.107293

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        257927.        2. MB
                95-   1        262144.        2. MB        236476.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        524288.        4. MB        494403.        4. MB


  Solver Memory allocated on core    0       =      144.568 MB
  Solver Memory allocated on core    1       =      124.086 MB
  Total Solver Memory allocated by all cores =      268.654 MB





  Performance statistics for DSP solver: icalls =     51

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2084974
     no. of nonzeroes in the factor l        =        12859738
     ratio of nonzeroes in factor (min/max)  =          0.7890
     number of super nodes                   =            1973
     maximum order of a front matrix         =             918
     maximum size of a front matrix          =          421821
     maximum size of a front trapezoid       =          358986
     no. of floating point ops for factor    =      3.8787D+09
     no. of floating point ops for solve     =      5.6506D+08
     ratio of flops for factor (min/max)     =          0.5795
     ratio of allocated memory (max/min)     =          1.1651
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.015625        0.008363
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.021374
     time (cpu & wall) for matrix distrib.   =        0.078125        0.067692
     time (cpu & wall) for numeric factor    =        0.171875        0.172725
     computational rate (gflops) for factor  =       22.566909       22.455855
     time (cpu & wall) for numeric solve     =        0.015625        0.014044
     computational rate (gflops) for solve   =       36.163939       40.233653
     effective I/O rate (GB/sec) for solve   =      134.731864      149.893935

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        257927.        2. MB
                95-   1        262144.        2. MB        236476.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        524288.        4. MB        494403.        4. MB


  Solver Memory allocated on core    0       =      144.567 MB
  Solver Memory allocated on core    1       =      124.084 MB
  Total Solver Memory allocated by all cores =      268.651 MB





  Performance statistics for DSP solver: icalls =     52

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2084974
     no. of nonzeroes in the factor l        =        12859738
     ratio of nonzeroes in factor (min/max)  =          0.7890
     number of super nodes                   =            1973
     maximum order of a front matrix         =             918
     maximum size of a front matrix          =          421821
     maximum size of a front trapezoid       =          358986
     no. of floating point ops for factor    =      3.8787D+09
     no. of floating point ops for solve     =      5.6506D+08
     ratio of flops for factor (min/max)     =          0.5795
     ratio of allocated memory (max/min)     =          1.1651
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.005753
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.031250        0.023721
     time (cpu & wall) for matrix distrib.   =        0.078125        0.107700
     time (cpu & wall) for numeric factor    =        0.187500        0.184674
     computational rate (gflops) for factor  =       20.686333       21.002923
     time (cpu & wall) for numeric solve     =        0.015625        0.014618
     computational rate (gflops) for solve   =       36.163939       38.654660
     effective I/O rate (GB/sec) for solve   =      134.731864      144.011258

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        257927.        2. MB
                95-   1        262144.        2. MB        236476.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        524288.        4. MB        494403.        4. MB


  Solver Memory allocated on core    0       =      144.568 MB
  Solver Memory allocated on core    1       =      124.085 MB
  Total Solver Memory allocated by all cores =      268.653 MB





  Performance statistics for DSP solver: icalls =     53

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2084974
     no. of nonzeroes in the factor l        =        12859738
     ratio of nonzeroes in factor (min/max)  =          0.7890
     number of super nodes                   =            1973
     maximum order of a front matrix         =             918
     maximum size of a front matrix          =          421821
     maximum size of a front trapezoid       =          358986
     no. of floating point ops for factor    =      3.8787D+09
     no. of floating point ops for solve     =      5.6506D+08
     ratio of flops for factor (min/max)     =          0.5795
     ratio of allocated memory (max/min)     =          1.1651
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.019625
     time (cpu & wall) for matrix distrib.   =        0.062500        0.062540
     time (cpu & wall) for numeric factor    =        0.156250        0.177670
     computational rate (gflops) for factor  =       24.823600       21.830803
     time (cpu & wall) for numeric solve     =        0.015625        0.013109
     computational rate (gflops) for solve   =       36.163939       43.105841
     effective I/O rate (GB/sec) for solve   =      134.731864      160.594519

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        257927.        2. MB
                95-   1        262144.        2. MB        236476.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        524288.        4. MB        494403.        4. MB


  Solver Memory allocated on core    0       =      144.568 MB
  Solver Memory allocated on core    1       =      124.085 MB
  Total Solver Memory allocated by all cores =      268.653 MB





  Performance statistics for DSP solver: icalls =     54

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2084974
     no. of nonzeroes in the factor l        =        12859738
     ratio of nonzeroes in factor (min/max)  =          0.7890
     number of super nodes                   =            1973
     maximum order of a front matrix         =             918
     maximum size of a front matrix          =          421821
     maximum size of a front trapezoid       =          358986
     no. of floating point ops for factor    =      3.8787D+09
     no. of floating point ops for solve     =      5.6506D+08
     ratio of flops for factor (min/max)     =          0.5795
     ratio of allocated memory (max/min)     =          1.1651
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.020155
     time (cpu & wall) for matrix distrib.   =        0.093750        0.101788
     time (cpu & wall) for numeric factor    =        0.218750        0.243569
     computational rate (gflops) for factor  =       17.731143       15.924396

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        257927.        2. MB
                95-   1        262144.        2. MB        236476.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        524288.        4. MB        494403.        4. MB


  Solver Memory allocated on core    0       =      144.568 MB
  Solver Memory allocated on core    1       =      124.085 MB
  Total Solver Memory allocated by all cores =      268.653 MB





  Performance statistics for DSP solver: icalls =     55

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2084974
     no. of nonzeroes in the factor l        =        12859738
     ratio of nonzeroes in factor (min/max)  =          0.7890
     number of super nodes                   =            1973
     maximum order of a front matrix         =             918
     maximum size of a front matrix          =          421821
     maximum size of a front trapezoid       =          358986
     no. of floating point ops for factor    =      3.8787D+09
     no. of floating point ops for solve     =      5.6506D+08
     ratio of flops for factor (min/max)     =          0.5795
     ratio of allocated memory (max/min)     =          1.1651
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.022588
     time (cpu & wall) for matrix distrib.   =        0.062500        0.063494
     time (cpu & wall) for numeric factor    =        0.203125        0.204805
     computational rate (gflops) for factor  =       19.095077       18.938469
     time (cpu & wall) for numeric solve     =        0.015625        0.014406
     computational rate (gflops) for solve   =       36.163939       39.223769
     effective I/O rate (GB/sec) for solve   =      134.731864      146.131526

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        257927.        2. MB
                95-   1        262144.        2. MB        236476.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        524288.        4. MB        494403.        4. MB


  Solver Memory allocated on core    0       =      144.568 MB
  Solver Memory allocated on core    1       =      124.085 MB
  Total Solver Memory allocated by all cores =      268.653 MB





  Performance statistics for DSP solver: icalls =     56

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2084974
     no. of nonzeroes in the factor l        =        12859738
     ratio of nonzeroes in factor (min/max)  =          0.7890
     number of super nodes                   =            1973
     maximum order of a front matrix         =             918
     maximum size of a front matrix          =          421821
     maximum size of a front trapezoid       =          358986
     no. of floating point ops for factor    =      3.8787D+09
     no. of floating point ops for solve     =      5.6506D+08
     ratio of flops for factor (min/max)     =          0.5795
     ratio of allocated memory (max/min)     =          1.1651
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.020123
     time (cpu & wall) for matrix distrib.   =        0.062500        0.062137
     time (cpu & wall) for numeric factor    =        0.234375        0.232847
     computational rate (gflops) for factor  =       16.549067       16.657687
     time (cpu & wall) for numeric solve     =        0.015625        0.013334
     computational rate (gflops) for solve   =       36.163939       42.378768
     effective I/O rate (GB/sec) for solve   =      134.731864      157.885745

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        257927.        2. MB
                95-   1        262144.        2. MB        236476.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        524288.        4. MB        494403.        4. MB


  Solver Memory allocated on core    0       =      144.568 MB
  Solver Memory allocated on core    1       =      124.085 MB
  Total Solver Memory allocated by all cores =      268.653 MB





  Performance statistics for DSP solver: icalls =     57

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2085298
     no. of nonzeroes in the factor l        =        12770088
     ratio of nonzeroes in factor (min/max)  =          0.8333
     number of super nodes                   =            1968
     maximum order of a front matrix         =             825
     maximum size of a front matrix          =          340725
     maximum size of a front trapezoid       =          287763
     no. of floating point ops for factor    =      3.7932D+09
     no. of floating point ops for solve     =      6.1269D+08
     ratio of flops for factor (min/max)     =          0.6852
     ratio of allocated memory (max/min)     =          1.1283
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.015625        0.016587
     time (cpu & wall) for ordering          =        0.140625        0.140781
     time (cpu & wall) for other matrix prep =        0.015625        0.038237
     time (cpu & wall) for value input       =        0.078125        0.060230
     time (cpu & wall) for matrix distrib.   =        0.156250        0.187942
     time (cpu & wall) for numeric factor    =        0.234375        0.245559
     computational rate (gflops) for factor  =       16.184406       15.447305

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        260235.        2. MB
                95-   1        262144.        2. MB        234133.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        524288.        4. MB        494368.        4. MB


  Solver Memory allocated on core    0       =      141.218 MB
  Solver Memory allocated on core    1       =      125.155 MB
  Total Solver Memory allocated by all cores =      266.373 MB





  Performance statistics for DSP solver: icalls =     58

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2085946
     no. of nonzeroes in the factor l        =        12667523
     ratio of nonzeroes in factor (min/max)  =          0.8867
     number of super nodes                   =            1966
     maximum order of a front matrix         =             819
     maximum size of a front matrix          =          335790
     maximum size of a front trapezoid       =          244335
     no. of floating point ops for factor    =      3.6701D+09
     no. of floating point ops for solve     =      6.5991D+08
     ratio of flops for factor (min/max)     =          0.7549
     ratio of allocated memory (max/min)     =          1.0546
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.015625        0.016831
     time (cpu & wall) for ordering          =        0.125000        0.140334
     time (cpu & wall) for other matrix prep =        0.031250        0.023692
     time (cpu & wall) for value input       =        0.062500        0.056808
     time (cpu & wall) for matrix distrib.   =        0.156250        0.169337
     time (cpu & wall) for numeric factor    =        0.203125        0.231439
     computational rate (gflops) for factor  =       18.067968       15.857573
     time (cpu & wall) for numeric solve     =        0.015625        0.013456
     computational rate (gflops) for solve   =       42.234099       49.041534
     effective I/O rate (GB/sec) for solve   =      157.346767      182.708454

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        255263.        2. MB
                95-   1        262144.        2. MB        238832.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        524288.        4. MB        494095.        4. MB


  Solver Memory allocated on core    0       =      135.168 MB
  Solver Memory allocated on core    1       =      128.165 MB
  Total Solver Memory allocated by all cores =      263.334 MB





  Performance statistics for DSP solver: icalls =     59

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2086864
     no. of nonzeroes in the factor l        =        12964029
     ratio of nonzeroes in factor (min/max)  =          0.9427
     number of super nodes                   =            1981
     maximum order of a front matrix         =             891
     maximum size of a front matrix          =          397386
     maximum size of a front trapezoid       =          275040
     no. of floating point ops for factor    =      3.9289D+09
     no. of floating point ops for solve     =      7.0829D+08
     ratio of flops for factor (min/max)     =          0.7538
     ratio of allocated memory (max/min)     =          1.0072
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.016726
     time (cpu & wall) for ordering          =        0.125000        0.150236
     time (cpu & wall) for other matrix prep =        0.015625        0.021659
     time (cpu & wall) for value input       =        0.046875        0.041652
     time (cpu & wall) for matrix distrib.   =        0.140625        0.143524
     time (cpu & wall) for numeric factor    =        0.296875        0.389272
     computational rate (gflops) for factor  =       13.234246       10.092983
     time (cpu & wall) for numeric solve     =        0.015625        0.021162
     computational rate (gflops) for solve   =       45.330550       33.470366
     effective I/O rate (GB/sec) for solve   =      168.882863      124.696727

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        246284.        2. MB
                95-   1        262144.        2. MB        250078.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        524288.        4. MB        496362.        4. MB


  Solver Memory allocated on core    0       =      135.518 MB
  Solver Memory allocated on core    1       =      134.547 MB
  Total Solver Memory allocated by all cores =      270.065 MB





  Performance statistics for DSP solver: icalls =     60

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2086864
     no. of nonzeroes in the factor l        =        12964029
     ratio of nonzeroes in factor (min/max)  =          0.9427
     number of super nodes                   =            1981
     maximum order of a front matrix         =             891
     maximum size of a front matrix          =          397386
     maximum size of a front trapezoid       =          275040
     no. of floating point ops for factor    =      3.9289D+09
     no. of floating point ops for solve     =      7.0829D+08
     ratio of flops for factor (min/max)     =          0.7538
     ratio of allocated memory (max/min)     =          1.0072
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.008109
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.020706
     time (cpu & wall) for matrix distrib.   =        0.062500        0.063205
     time (cpu & wall) for numeric factor    =        0.156250        0.170740
     computational rate (gflops) for factor  =       25.145068       23.011150
     time (cpu & wall) for numeric solve     =        0.015625        0.016307
     computational rate (gflops) for solve   =       45.330550       43.434446
     effective I/O rate (GB/sec) for solve   =      168.882863      161.818762

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        246284.        2. MB
                95-   1        262144.        2. MB        250078.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        524288.        4. MB        496362.        4. MB


  Solver Memory allocated on core    0       =      135.519 MB
  Solver Memory allocated on core    1       =      134.549 MB
  Total Solver Memory allocated by all cores =      270.069 MB





  Performance statistics for DSP solver: icalls =     61

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2086864
     no. of nonzeroes in the factor l        =        12964029
     ratio of nonzeroes in factor (min/max)  =          0.9427
     number of super nodes                   =            1981
     maximum order of a front matrix         =             891
     maximum size of a front matrix          =          397386
     maximum size of a front trapezoid       =          275040
     no. of floating point ops for factor    =      3.9289D+09
     no. of floating point ops for solve     =      7.0829D+08
     ratio of flops for factor (min/max)     =          0.7538
     ratio of allocated memory (max/min)     =          1.0072
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.015625        0.008447
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.021649
     time (cpu & wall) for matrix distrib.   =        0.078125        0.083332
     time (cpu & wall) for numeric factor    =        0.203125        0.195279
     computational rate (gflops) for factor  =       19.342360       20.119515

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        246284.        2. MB
                95-   1        262144.        2. MB        250078.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        524288.        4. MB        496362.        4. MB


  Solver Memory allocated on core    0       =      135.517 MB
  Solver Memory allocated on core    1       =      134.547 MB
  Total Solver Memory allocated by all cores =      270.064 MB





  Performance statistics for DSP solver: icalls =     62

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2086864
     no. of nonzeroes in the factor l        =        12964029
     ratio of nonzeroes in factor (min/max)  =          0.9427
     number of super nodes                   =            1981
     maximum order of a front matrix         =             891
     maximum size of a front matrix          =          397386
     maximum size of a front trapezoid       =          275040
     no. of floating point ops for factor    =      3.9289D+09
     no. of floating point ops for solve     =      7.0829D+08
     ratio of flops for factor (min/max)     =          0.7538
     ratio of allocated memory (max/min)     =          1.0072
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.008461
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.020902
     time (cpu & wall) for matrix distrib.   =        0.078125        0.086810
     time (cpu & wall) for numeric factor    =        0.171875        0.169224
     computational rate (gflops) for factor  =       22.859152       23.217255
     time (cpu & wall) for numeric solve     =        0.015625        0.014337
     computational rate (gflops) for solve   =       45.330550       49.402588
     effective I/O rate (GB/sec) for solve   =      168.882863      184.053591

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        246284.        2. MB
                95-   1        262144.        2. MB        250078.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        524288.        4. MB        496362.        4. MB


  Solver Memory allocated on core    0       =      135.514 MB
  Solver Memory allocated on core    1       =      134.544 MB
  Total Solver Memory allocated by all cores =      270.059 MB





  Performance statistics for DSP solver: icalls =     63

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2086864
     no. of nonzeroes in the factor l        =        12964029
     ratio of nonzeroes in factor (min/max)  =          0.9427
     number of super nodes                   =            1981
     maximum order of a front matrix         =             891
     maximum size of a front matrix          =          397386
     maximum size of a front trapezoid       =          275040
     no. of floating point ops for factor    =      3.9289D+09
     no. of floating point ops for solve     =      7.0829D+08
     ratio of flops for factor (min/max)     =          0.7538
     ratio of allocated memory (max/min)     =          1.0072
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.019906
     time (cpu & wall) for matrix distrib.   =        0.062500        0.068017
     time (cpu & wall) for numeric factor    =        0.171875        0.163840
     computational rate (gflops) for factor  =       22.859152       23.980147
     time (cpu & wall) for numeric solve     =        0.015625        0.018692
     computational rate (gflops) for solve   =       45.330550       37.893079
     effective I/O rate (GB/sec) for solve   =      168.882863      141.173923

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        246284.        2. MB
                95-   1        262144.        2. MB        250078.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        524288.        4. MB        496362.        4. MB


  Solver Memory allocated on core    0       =      135.514 MB
  Solver Memory allocated on core    1       =      134.544 MB
  Total Solver Memory allocated by all cores =      270.059 MB





  Performance statistics for DSP solver: icalls =     64

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2086702
     no. of nonzeroes in the factor l        =        12795392
     ratio of nonzeroes in factor (min/max)  =          0.8680
     number of super nodes                   =            1981
     maximum order of a front matrix         =             816
     maximum size of a front matrix          =          333336
     maximum size of a front trapezoid       =          287199
     no. of floating point ops for factor    =      3.7665D+09
     no. of floating point ops for solve     =      7.5602D+08
     ratio of flops for factor (min/max)     =          0.7070
     ratio of allocated memory (max/min)     =          1.0867
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.015625        0.016453
     time (cpu & wall) for ordering          =        0.109375        0.109930
     time (cpu & wall) for other matrix prep =        0.015625        0.015319
     time (cpu & wall) for value input       =        0.046875        0.049537
     time (cpu & wall) for matrix distrib.   =        0.140625        0.129860
     time (cpu & wall) for numeric factor    =        0.156250        0.155846
     computational rate (gflops) for factor  =       24.105579       24.167990
     time (cpu & wall) for numeric solve     =        0.015625        0.013410
     computational rate (gflops) for solve   =       48.385246       56.376450
     effective I/O rate (GB/sec) for solve   =      180.263397      210.035314

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        256733.        2. MB
                95-   1        262144.        2. MB        238827.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        524288.        4. MB        495560.        4. MB


  Solver Memory allocated on core    0       =      139.060 MB
  Solver Memory allocated on core    1       =      127.967 MB
  Total Solver Memory allocated by all cores =      267.028 MB





  Performance statistics for DSP solver: icalls =     65

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2086702
     no. of nonzeroes in the factor l        =        12795392
     ratio of nonzeroes in factor (min/max)  =          0.8680
     number of super nodes                   =            1981
     maximum order of a front matrix         =             816
     maximum size of a front matrix          =          333336
     maximum size of a front trapezoid       =          287199
     no. of floating point ops for factor    =      3.7665D+09
     no. of floating point ops for solve     =      7.5602D+08
     ratio of flops for factor (min/max)     =          0.7070
     ratio of allocated memory (max/min)     =          1.0867
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.021567
     time (cpu & wall) for matrix distrib.   =        0.062500        0.069131
     time (cpu & wall) for numeric factor    =        0.171875        0.160645
     computational rate (gflops) for factor  =       21.914163       23.446073
     time (cpu & wall) for numeric solve     =        0.015625        0.015158
     computational rate (gflops) for solve   =       48.385246       49.876926
     effective I/O rate (GB/sec) for solve   =      180.263397      185.820776

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        256733.        2. MB
                95-   1        262144.        2. MB        238827.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        524288.        4. MB        495560.        4. MB


  Solver Memory allocated on core    0       =      139.060 MB
  Solver Memory allocated on core    1       =      127.967 MB
  Total Solver Memory allocated by all cores =      267.028 MB





  Performance statistics for DSP solver: icalls =     66

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           56545
     no. of nonzeroes in lower triangle of a =         2086702
     no. of nonzeroes in the factor l        =        12795392
     ratio of nonzeroes in factor (min/max)  =          0.8680
     number of super nodes                   =            1981
     maximum order of a front matrix         =             816
     maximum size of a front matrix          =          333336
     maximum size of a front trapezoid       =          287199
     no. of floating point ops for factor    =      3.7665D+09
     no. of floating point ops for solve     =      7.5602D+08
     ratio of flops for factor (min/max)     =          0.7070
     ratio of allocated memory (max/min)     =          1.0867
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              12
     factorization panel size                =             128
     number of processes used                =               2
     number of threads per process used      =               1
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.046875        0.041063
     time (cpu & wall) for matrix distrib.   =        0.078125        0.108663
     time (cpu & wall) for numeric factor    =        0.250000        0.243244
     computational rate (gflops) for factor  =       15.065987       15.484419
     time (cpu & wall) for numeric solve     =        0.031250        0.035009
     computational rate (gflops) for solve   =       24.192623       21.595250
     effective I/O rate (GB/sec) for solve   =       90.131698       80.454962

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        262144.        2. MB        256733.        2. MB
                95-   1        262144.        2. MB        238827.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        524288.        4. MB        495560.        4. MB


  Solver Memory allocated on core    0       =      139.060 MB
  Solver Memory allocated on core    1       =      127.967 MB
  Total Solver Memory allocated by all cores =      267.028 MB

